### ISSUE TITLE
Not Showing All Photos of Album

### ISSUE THREAD

**Issue by Maninarang** [esteban-uo/picasa#14]
@esteban-uo - i am having a problem to list all the photos of album.I have 20000+ photos in a particular album.When i get the photos using albumid, startindex and maxresult(using 1000) parameters it works well till 11000 photos but when i try to fetch 11001 photo it gives me (status code 400 response invalid request) error.

**Comment by martinlarka** [comment]
I had the same problem, got at fix for it in this PR #18

**Comment by esteban-uo** [comment]
@Maninarang got it working this way:

“I got it working.. worked by getting the subalbums” I’ll play with his findings and your PR @martinlarka

**Comment by Maninarang** [comment]
Thanx... I already got it working

**Comment by jlengrand** [comment]
Is this still an issue then or did #18 fix it?

**Comment by martinlarka** [comment]
I would say that it's fixed.

**Comment by jlengrand** [comment]
Alright, cool!
