### ISSUE TITLE
Fetch-based version for the browser

### ISSUE THREAD

**Issue by WietseWind** [esteban-uo/picasa#24]
Hi,

I added a request-method using the Fetch-API. This way the code works in the browser 👍 

My commit is not suited for a pull request, but it might help someone?
https://github.com/WietseWind/picasa/commit/4939dd3b823dcbc816c0bbd427c8d4e7aa9591ea

You can now do something like this (in a project with Vue-Webpack / browserify / ...)

```
window.CORSPROXY = 'https://cors-anywhere.herokuapp.com'

const Picasa = require('picasa')
const picasa = new Picasa()

window.gapi.load('auth2', () => {
    window.gapi.auth2.init(this.gSignInParams).then((gauth) => {
        if (gauth.isSignedIn.get()) {
            console.log('Logged In')

            picasa.getAlbums(window.gapi.client.getToken().access_token, null, (error, albums) => {
                if (error) return
                console.log(albums)
            })
        } else {
            console.log('Not logged in')
        }
    })
})
```

-- P.S. Are you on Twitter? I'd love to send you some $XRP to thank you for your awesome work :)

**Comment by esteban-uo** [comment]
@WietseWind awesome Job! my twitter account is @e_uscanga_olea I would appreciate to stay in touch instead of your generous donation. Many thanks for your offer! 

I'm planning to transform this module soon into browser/node compatible version and I'll reuse your code 💪

**Comment by WietseWind** [comment]
[Done](https://xwenrnk.dlvr.cloud/pasted_1.png) :) 👍
