### ISSUE TITLE
"TypeError: Cannot read property 'executeRequest' of undefined"

### ISSUE THREAD

**Issue by christiangenco** [esteban-uo/picasa#26]
In going through the OAuth flow, I'm getting "TypeError: Cannot read property 'executeRequest' of undefined" when executing `picasa.getTokens(config, code)`.

The stack trace says this error happens on picasa.js:376:

<img width="525" alt="screen shot 2018-05-07 at 10 14 21 pm" src="https://user-images.githubusercontent.com/179361/39771368-82ea7998-52b7-11e8-8005-de7f9f53a4c8.png">

My code is running in a browser, and looks like this:

```javascript
import Picasa from "picasa";
const picasa = new Picasa();

const clientId = "...apps.googleusercontent.com";
const clientSecret = "SEEEEEECRET";
const redirectURI = "http://localhost:3000/auth";

export const getAuthURL = () => {
  const config = {
    clientId,
    redirectURI
  };

  const authURL = picasa.getAuthURL(config);
  return authURL;
};

const getTokens = async code => {
  const config = {
    clientId,
    clientSecret,
    redirectURI
  };

  const tokens = await picasa.getTokens(config, code);
  return tokens;
};

// 1. send user to getAuthURL
// 2. grab the `code` from the query string at /auth and call `getTokens(code).then(tokens => {})`

```

What am I doing wrong?

**Comment by esteban-uo** [comment]
@christiangenco seems to be a bug, I'll fix it in between tomorrow and the day after tomorrow if you don't mind. Many thanks for reporting it!

**Comment by christiangenco** [comment]
@esteban-uo cool - thanks! 🕺

**Comment by esteban-uo** [comment]
@christiangenco sorry for the very late answer. I tried to reproduce the error with the version `1.0.7`, without an issue.

`My code is running in a browser, and looks like this:`, the library is meant to be - for now - compatible with Nodejs, not with the browser. Could you describe me more how you are: installing and executing it? I hope I'll build soon a version so that you can also run it with the browser/nodejs. Thanks!

**Comment by christiangenco** [comment]
> Could you describe me more how you are: installing and executing it?

Sure! I'm making a React app that I'd love to live entirely in a browser to more quickly add photos to albums (think: keyboard shortcut driven photo triaging).

I created the app with [`create-react-app`](https://github.com/facebook/create-react-app), then ran `yarn add picasa` to install your library.

That oAuth flow code from my first post is then run in response to a "Log in" button press.

Is that what you need?

**Comment by esteban-uo** [comment]
@christiangenco I'm really sorry that I can't help you right now, but as I described previously, this library is not browser compatible - if you would need so, you might want to check this out https://github.com/esteban-uo/picasa/issues/24
