### ISSUE TITLE
any chance to make this code to support nodejs 0.10.x?

### ISSUE THREAD

**Issue by wangpingsx** [esteban-uo/picasa#3]
Hi, 

The ES6 syntax needs nodejs 4.0+.

I was wondering is there any chance to degrade the code to support 0.10.x?

Thanks,
Peter

**Comment by esteban-uo** [comment]
Hey @wangpingsx 

That one is a tough one, but I could come with a solution to support under node 4.x.x. Any chance for you to use Babel instead? https://babeljs.io/docs/usage/require/

Greetings,
Esteban.

**Comment by esteban-uo** [comment]
Closed due no answer, please just open the issue again @wangpingsx to see if we can arrange something else.
