### ISSUE TITLE
Uploaded Videos not processing

### ISSUE THREAD

**Issue by Mattze96** [esteban-uo/picasa#8]
Hello,
let me first thank you for this great piece of software.

When i upload some videos to my picasaweb/google-photo site they don't get converted and it says: 'Your video will be ready soon' and via getPhotos() the videostatus says 'pending'

Do you experience the same anomaly?

**Comment by Mattze96** [comment]
```
function postVideo (accessToken, albumId, videoData, callback) {
  const requestQuery = querystring.stringify({
    alt          : FETCH_AS_JSON,
    access_token : accessToken
  })

  const videoInfoAtom = `<entry xmlns="http://www.w3.org/2005/Atom">
                          <title>${videoData.title}</title>
                          <summary>${videoData.summary}</summary>
                          <category scheme="http://schemas.google.com/g/2005#kind" term="http://schemas.google.com/photos/2007#photo"/>
                        </entry>`

  const requestOptions = {
    url : `${PICASA_SCOPE}${PICASA_API_FEED_PATH}/albumid/${albumId}?${requestQuery}`,
    headers: {
      'GData-Version': '2'
    },
    multipart : [
      {'Content-Type' : 'application/atom+xml', body : videoInfoAtom},
      {'Content-Type' : videoData.contentType, body : videoData.binary}
    ]
  }

  this.executeRequest('post', requestOptions, (error, body) => {
    if (error) return callback(error)

    const video = parseEntry(body.entry, photoSchema)

    callback(error, video)
  })
}

```

**Comment by esteban-uo** [comment]
hi @Mattze96! I thank you for your words and the new postVideo function!

I just tested and also experienced the same behaviour, even with a video that I uploaded manually via google photos. I will investigate this issue and come back to you,

Greetings!

**Comment by esteban-uo** [comment]
@Mattze96 
Seems to be it is a problem with Picasa API

https://groups.google.com/forum/#!msg/google-picasa-data-api/8e_QPXmWS6A/G8AfwqFKIwAJ

or

https://groups.google.com/forum/#!msg/google-picasa-data-api/36IXQS4proM/lVkK9FGeHaEJ

or maybe, not clear documentation. I believe it is possible, because with the official client for Java seems to be works fine:

https://groups.google.com/forum/#!topic/google-picasa-data-api/cM4qr1D75hE

I'm debugging some different clients to see what kind of payload is sent and what we don't send.

**Comment by alaxwork** [comment]
Hi @esteban-uo, I am using curl command for api communication: curl -H "GData-Version: 3" -H "Content-Type: multipart/related" -H "Authorization: Bearer {access token}" --form "data=@1.xml;type=application/atom+xml" --form "data=@1.mp4;type=video/mpeg4" -X POST https://picasaweb.google.com/data/feed/api/user/{userid}/albumid/{albumId} -i -v
I got 201 status back, it seems good, but the the video has status 'pending' and don't change it.
Could you help me

1.xml:
`<entry xmlns='http://www.w3.org/2005/Atom'>
	<title>test video</title>
	<summary>some summary</summary>
	<category scheme="http://schemas.google.com/g/2005#kind" term="http://schemas.google.com/photos/2007#photo"/>
</entry>`

**Comment by esteban-uo** [comment]
@alaxwork it seems to be a problem from Picasa API. I contacted the support but I'm still waiting for an answer. Once I get something I'm going to update this thread.
